<?php if ( ! defined('BASEPATH')) exit('No direct script access allowed');

/**
 * Created by Console.
 * User: Amine Maagoul
 * Date: {date}
 * Time: {time}
 */

class Modules_manager extends MY_Controller {

    public function __construct(){
        parent::__construct();


        /////// register module ///////
        $data = array(
            "version_code"  =>1,
            "version_name"  => "1.0.1 Beta",
            "order"     =>1
        );
        FModuleLoader::register($this,$data);

        TemplateManager::registerMenuSetting(
            'modules_manager',
            "modules_manager/menu_setting",
            7
        );


    }
    public function onLoaded()
    {
        parent::onLoaded(); // TODO: Change the autogenerated stub
    }


    public function error404(){



    }






}

/* End of file CmsDB.php */